### ISSUE TITLE
no icons in font-awesome sets

### ISSUE THREAD

**Issue by ibstelix** [Xaviju/inkscape-open-symbols#101]
Hello,
thank very much you for this great job.
For font-awesome sets i cannot see icons after import in inkscape et even if i open it online,
same for gnome.
Best regards

**Comment by Xaviju** [comment]
Since this is a symbol, you shouldn't be able to see anything online. 
If you open the symbols in Inkscape it should be visible under the symbols panel. 
Did you follow the readme instructions to import and use the symbols?
