### ISSUE TITLE
Replace Material Icons

### ISSUE THREAD

**Issue by dszidi** [Xaviju/inkscape-open-symbols#103]
First of all I want to mention that I was about to embark on creating symbols for Inkscape when I came across this repo. Bravo and kudos to you for getting this started.  I just wanted to strongly suggest using the material icon set from https://materialdesignicons.com . 

The reason being is that they keep up to date with the upstream icon set, but also have a lot of very good high quality community contributed icons as well. One that we were desperately in need of at the FreeNAS project was a hard disk icon. No such icon was available in the standard collection, but the extended collection I linked to has all that and much more.

**Comment by Xaviju** [comment]
Thanks for the suggestion!
The symbol sets offered in this repo will only be the official ones to keep design consistency. In any case, this resource is very interesting.
