### ISSUE TITLE
Font Awesome not added in 18.04

### ISSUE THREAD

**Issue by meetdilip** [Xaviju/inkscape-open-symbols#108]
When I tried in Ubuntu 18.04

`sudo apt-get install inkscape-open-symbols`

most of the icons are available through Inkscape, except Font Awesome. How can I add Font Awesome to symbols now ( currently not present ).

**Comment by Xaviju** [comment]
Sorry, we don't manage `apt` installation through this repo.
To open an issue to ubuntu/debian/* please add it to their repos 

- https://packages.debian.org/sid/inkscape-open-symbols
- https://packages.ubuntu.com/cosmic/inkscape-open-symbols

To add it manually, check the instructions on the readme file on this repo.
