### ISSUE TITLE
Add Genericons

### ISSUE THREAD

**Issue by PanderMusubi** [Xaviju/inkscape-open-symbols#12]
Please add Genericons https://github.com/Automattic/Genericons You can drop me a line for testing again of you want. Thanks

**Comment by Xaviju** [comment]
Started working on this icons: https://github.com/Xaviju/inkscape-open-symbols/commit/111106b96ce4c53e19839307d26a9e97eea9200f

**Comment by Xaviju** [comment]
Added here: https://github.com/Xaviju/inkscape-open-symbols/commit/2c13fc3c91f7a37ac642826766a7552cd9d7c8ca

Please test and add issues if required.

Thanks!

**Comment by PanderMusubi** [comment]
Test OK. Thanks!

You can add http://genericons.com/ to the README.md for these icons.
