### ISSUE TITLE
Link in project not working

### ISSUE THREAD

**Issue by victorwestmann** [Xaviju/inkscape-open-symbols#15]
Hi there. Very happy to have found this project. Already installed in my Windows system and it works perfectly.

One question though: the link that would teach me how to create new symbol libraries in Inkscape is not working: https://github.com/Xaviju/inkscape-open-symbols/blob/master/Creating%20symbol%20libraries%20in%20Inkscape

Is it wrongly linked or doesn`t it exist?

**Comment by Xaviju** [comment]
It is working for me, this is the right link on the README.md https://medium.com/@xaviju/creating-your-own-symbol-library-in-inkscape-0-91-and-make-your-front-end-developer-you-338588137aaf

**Comment by PanderMusubi** [comment]
Are you sure that this is fixed for the README.md?

**Comment by victorwestmann** [comment]
It is not the end of the world.... but indeed there is a dead link in README.MD :)

**Comment by victorwestmann** [comment]
I sent a pull request with minor additions to the file. Hope it helps! :)
