### ISSUE TITLE
Add information in README.MD on how to convert symbols to paths

### ISSUE THREAD

**Issue by victorwestmann** [Xaviju/inkscape-open-symbols#17]
Such as:

How to convert symbols to paths in Inkscape?
1. Go to Edit > Clone > Unlink (shift + Alt + D),
2. Ungroup (Shift + Ctrl + G),
3. Profit!

Hope it helps!

**Comment by Xaviju** [comment]
Not sure if it should be added to the readme because its not part of the symbol library development process but instead an inkscape feature to convert symbols to paths and edit them, where do you think it should be added? How are you using it to create symbols?

**Comment by victorwestmann** [comment]
Maybe you`re right. This is not needed or helpful to create the library
symbols but to use them. You can close this issue if you wish then. Just
tried to add more useful info to the libraries.



--Victor Westmann

2015-11-08 10:10 GMT-02:00 Xaviju <notifications@github.com>:

**Comment by victorwestmann** [comment]
This video could be added alongside your link. I believe it would be very useful for new contributors.

**Comment by Xaviju** [comment]
Wow, that was fast! Thanks @victorwestmann
