### ISSUE TITLE
Support iconset Dashicons from WordPress

### ISSUE THREAD

**Issue by PanderMusubi** [Xaviju/inkscape-open-symbols#18]
Please, support iconset Dashicons from WordPress. Sources are found at https://github.com/WordPress/dashicons and examples are found at https://developer.wordpress.org/resource/dashicons/

License is GPLv2

**Comment by victorwestmann** [comment]
You can also help us make this library become available! Help us out!

a.) Follow the link: https://www.youtube.com/watch?v=jdaGB0zCdHw
b.) And download the font in the URL: https://s.w.org/wp-includes/fonts/dashicons.ttf

1.) I believe that you should install this font in your system
2.) Open Inkscape
3.) Try to use each font glyph for it to appear in Inkscape canvas
4.) and follow the video instructions cited in a we have a strong chace of success!

Try all this and let us know if it worked. Thanks.

**Comment by Xaviju** [comment]
Thanks for the idea @PanderMusubi the icons look great.

**Comment by Xaviju** [comment]
This icons are already available :tada: https://github.com/Xaviju/inkscape-open-symbols/commit/39738e6f7e03e5b8b48d8d823a472eeed505eb2e

Enjoy
