### ISSUE TITLE
Errors in GNOME action and app symbols

### ISSUE THREAD

**Issue by PanderMusubi** [Xaviju/inkscape-open-symbols#21]
While testing all symbols today, I found the following error on the command line while starting Inkscape and having all SVG files from this project installed in ~/.config/inkscape/symbols Please fix this and let me know when I can retest this.

    ~/.config/inkscape/symbols/gnome-action.svg:191: parser error : StartTag: invalid element name
            < </symbol>
             ^
    ~/.config/inkscape/symbols/gnome-action.svg:277: parser error : Opening and ending tag mismatch: symbol line 271 and g
            </g>
                ^
    ~/.config/inkscape/symbols/gnome-action.svg:278: parser error : Opening and ending tag mismatch: defs line 29 and symbol
        </symbol>
                 ^
    ~/.config/inkscape/symbols/gnome-action.svg:433: parser error : Opening and ending tag mismatch: symbol line 425 and svg
        </svg>
              ^
    ~/.config/inkscape/symbols/gnome-action.svg:435: parser error : Opening and ending tag mismatch: svg line 1 and g
    </g>
        ^
    ~/.config/inkscape/symbols/gnome-action.svg:436: parser error : Extra content at the end of the document
    </symbol>
    ^
    ~/.config/inkscape/symbols/gnome-app.svg:261: parser error : error parsing attribute name
                    <pathd='m 331.90625,654.96875 a 1.0001221,1.0001221 0 1 0 -0.031
                          ^
    ~/.config/inkscape/symbols/gnome-app.svg:261: parser error : attributes construct error
                    <pathd='m 331.90625,654.96875 a 1.0001221,1.0001221 0 1 0 -0.031
                          ^
    ~/.config/inkscape/symbols/gnome-app.svg:261: parser error : Couldn't find end of Start Tag pathd line 261
                    <pathd='m 331.90625,654.96875 a 1.0001221,1.0001221 0 1 0 -0.031
                          ^
    ~/.config/inkscape/symbols/gnome-app.svg:333: parser error : Opening and ending tag mismatch: defs line 29 and svg
        </svg>
              ^
    ~/.config/inkscape/symbols/gnome-app.svg:334: parser error : Premature end of data in tag svg line 1
    
    ^
    
    ** (inkscape:14331): WARNING **: unknown type: svg:pathd

**Comment by Xaviju** [comment]
Seems like the code is broken somewhere, great catch @PanderMusubi !!

**Comment by Xaviju** [comment]
Sadly, those icons should be redone. :(

**Comment by PanderMusubi** [comment]
Don't follow. Waht exactly?
