### ISSUE TITLE
Licences of the respective Icon Sets could be more visible

### ISSUE THREAD

**Issue by Moini** [Xaviju/inkscape-open-symbols#32]
I've been looking to find the licences for the icon sets. While the licence of the repo is GPLv2, the licences of the respective icon sets differ, some are incompatible (I don't think it's a problem, as this is just a compilation, but IANAL) - and I cannot find them inside the files themselves.

I think it would be comfortable for the user to see how and under which circumstances they may use the icons directly in the user interface. This could be made possible by, for example, putting the licence tag (i.e. something like CC-By-SA Google) into the name of the icon set, by adding the licence as an extra tag into the symbol itself, or at least by writing the licence into the files (but that has a very low visibility).

It's hard to not break the licence agreement for the average user who just downloads the symbol sets and uses them in their work. Many (e.g. twitter, emojione, ...) actually ask for attribution when you use them on a website or in an app.

A hint in the readme file about this would be helpful, too.

**Comment by Xaviju** [comment]
You're right.
We should add the icons license in the SVG sprite metadata and in the README next to the icon set name.

**Comment by Xaviju** [comment]
I've updated all of them with their respective licenses. https://github.com/Xaviju/inkscape-open-symbols/commit/4292a7daac7dd10ec7bea5e84441b4d62e7e445c

**Comment by Moini** [comment]
Thank you, @Xaviju !!!

**Comment by Moini** [comment]
(didn't you say you wanted to add the info to the readme, too?...)

**Comment by Xaviju** [comment]
Yes! reopening!

**Comment by victorwestmann** [comment]
Emoji one = CC BY 4.0 (Attribution) http://emojione.com/licensing/
Font Awesome = SIL OFL 1.1 http://fontawesome.io/license/ 
Genericons = GPL v2 LICENSE.TXT from https://genericons.com/
Gnome Icon Theme = CC BY SA 3.0 https://github.com/GNOME/gnome-icon-theme-symbolic/blob/master/COPYING
Humble UI = ? https://github.com/Xaviju/inkscape-open-symbols/wiki/Humble-UI
Google Material Design Icons = Apache 2 https://github.com/google/material-design-icons
Taiga Icons = CC BY SA 4.0 https://github.com/taigaio/taiga-design

**Comment by Xaviju** [comment]
Thanks @victorwestmann I'll add it to the README

**Comment by Moini** [comment]
Thank you, @victorwestmann and @Xaviju !
