### ISSUE TITLE
Remove execute rights from file internet-symbols.svg

### ISSUE THREAD

**Issue by PanderMusubi** [Xaviju/inkscape-open-symbols#35]
Please, remove execute rights from file internet-symbols.svg

**Comment by Xaviju** [comment]
I have not a good knowledge of file permissions. Could you check if its fixed now? https://github.com/Xaviju/inkscape-open-symbols/commit/58182309378ca0eed2e45a6b6aeb7cb04abfb60f
If not, could you show me how to remove it?

**Comment by PanderMusubi** [comment]
Which operating system are you using?

**Comment by Xaviju** [comment]
Linux. Specifically I am using Ubuntu or Manjaro.

**Comment by PanderMusubi** [comment]
Go in a terminal to each directory that contains SVG files and type:

    chmod a-x *.svg

**Comment by Xaviju** [comment]
I've made it and no changes occurred in any symbol set. Nothing to commit

**Comment by PanderMusubi** [comment]
then all is fine. I also checked latest download and there all is okay too.

**Comment by Xaviju** [comment]
Thanks!
