### ISSUE TITLE
Errors with emoji one

### ISSUE THREAD

**Issue by PanderMusubi** [Xaviju/inkscape-open-symbols#37]
Please fix these erros with emoji one:

    .config/inkscape/symbols/emojione.svg:13285: parser error : Opening and ending tag mismatch: desc line 14 and sv
    </svg>
          ^
    .config/inkscape/symbols/emojione.svg:13286: parser error : Premature end of data in tag desc line 14
    ^
    .config/inkscape/symbols/emojione.svg:13286: parser error : Premature end of data in tag svg line 2
    ^

**Comment by PanderMusubi** [comment]
Is this still an issue? I don't see it when I use the symbols installed via apt on Linux or in ~/.config. If nobody can reproduce this on Linux, this can be closed.

**Comment by Xaviju** [comment]
I think it was fixed on an unrelated PR. Closing it. Reopen if necessary.

Thanks @PanderMusubi
