### ISSUE TITLE
Add VRT network icons for Visio-like designs

### ISSUE THREAD

**Issue by PanderMusubi** [Xaviju/inkscape-open-symbols#41]
Please add VRT network icons for Visio-like designs. see http://libregraphicsworld.org/blog/entry/diagramming-with-bling and http://www.vrt.com.au/downloads/vrt-network-equipment

These icons are available in a vector format for LibreOffice and OpenOffice.org and need to get converted to SVG. For this a conversion script should be developed.

**Comment by Xaviju** [comment]
This issue was already opened by @PanderMusubi here #25 
Since they do not provide SVG files I opened an issue that is still not solved: https://bitbucket.org/vrtsystems/odf-extension-vrt-network-equipment/issues/3/icons-in-other-formats

Please request this SVG icons to the VRT team 

Thanks
