### ISSUE TITLE
add Open Source license to Weatherize symbols

### ISSUE THREAD

**Issue by legrostdg** [Xaviju/inkscape-open-symbols#44]
In the README, Weatherize's license is set to "No license or website found.", so it is proprietary. If so, shouldn't it be removed from inkscape-open-symbols?

**Comment by legrostdg** [comment]
@jlar0che: You are the author listed in inkscape-open-symbols's README.md. Would you consider publishing Weatherize with an open source license?

**Comment by Xaviju** [comment]
You are right @legrostdg if they are not open it should be removed. Sorry and thanks for pointing thi out.
Hopefully, @jlar0che will license this amazing symbol set as Open Source.

What do you say @jlar0che ?

**Comment by jlar0che** [comment]
That seems to be a mistake. Everything I've done for Inkscape Open Symbols is Open Source.

**Comment by jlar0che** [comment]
Feel free to change the license on all my contributions to Open Source

**Comment by Moini** [comment]
@jlar0che: There are quite a lot of different F(L)OSS licences, and nobody but you can add one to your works :) ('Open Source' only means that people are allowed to read the source code, this doesn't say anything about sharing, making derivations, attribution,...).

I'd suggest you use CC0, CC-By, or CC-By-SA, as the licenced contents is basically art, not so much code.
If you use CC-By-SA or CC-By, I think it would be a nice extra to allow people to use the icons without linking to your site, the licence and mentioning your name, and to only have the licence apply if they want to publish derivations of the set. This would have to be mentioned separately.

For a licence choosing aid, see also https://creativecommons.org/choose/?lang=en

**Comment by jlar0che** [comment]
I was trying to speed up this process because I won't be able to get to it
since I'm out of town. I'll get to it, but not for a few days at least - I
won't get back home till the end of the first week of January.

**Comment by Xaviju** [comment]
No problem @jlar0che thanks for your interest in adding an Open Source license! Please let us know which license have you chosen once you did it so we can reference it from the repo so everyone knows that it can be used safely. 
It would be even better if you publish you set in your github profile and add an OS License there.

Let me know if I can help

**Comment by legrostdg** [comment]
@jlar0che just to be sure: you are the author of weather icons (and did not only convert these to svg from another source), right?

**Comment by Xaviju** [comment]
Yes, he did it according to this PR: https://github.com/Xaviju/inkscape-open-symbols/pull/28

**Comment by legrostdg** [comment]
OK!

**Comment by legrostdg** [comment]
@jlar0che any update? We're waiting for this before making a release (#45) and packaging it for Debian.

Thanks!

**Comment by jlar0che** [comment]
All my contributions can fall under the CC-By-SA. Thanks.

**Comment by legrostdg** [comment]
I think you need to be more precise... There are multiple version of CC-By-SA. What would really help would be a repo with your symbols, the name of copyright owner and the complete text of the license chosen.

**Comment by legrostdg** [comment]
See for example https://github.com/GNOME/gnome-icon-theme-symbolic and https://github.com/GNOME/gnome-icon-theme-symbolic/blob/master/COPYING

**Comment by Xaviju** [comment]
@legrostdg I think would be enough for the release if @jlar0che could answer this two questions and give us the result: https://creativecommons.org/choose/?lang=en

I could add the info it to the icon license and finally publish it. 
Publishing the icons in a repo and adding the LICENSE file would be perfect but depends on the available time.

**Comment by jlar0che** [comment]
The answer is yes, and yes. See below:
Allow adaptations of your work to be shared?

   - Yes
   - No
   - Yes, as long as others share alike

Allow commercial uses of your work?

   - Yes
   - No

**Comment by Xaviju** [comment]
Thanks @jlar0che! The license will be **Creative Commons Attribution 4.0 International License**. I'll update the symbol set with your license.

**Comment by Xaviju** [comment]
https://github.com/Xaviju/inkscape-open-symbols/commit/8583275aaf44c021c96890230f9a74077918eabe
