### ISSUE TITLE
release inkscape-open-symbols

### ISSUE THREAD

**Issue by legrostdg** [Xaviju/inkscape-open-symbols#45]
It would be great to have a github release of inkscape-open-symbols. (It would help packaging for Debian)

**Comment by Xaviju** [comment]
Thanks for the suggestion. I didn't know this could be useful for packaging! 
I guess once its sorted out all the required information from weather icons it would be ok to create a **1.0.0 release**. What do you think?
Will I need to include all the svg files zipped so it can be simply unzipped into the inkscape symbols folder? Or maybe only creating the release tag would be enough?
Thanks for your help :wink:

**Comment by legrostdg** [comment]
It's easy to create releases on github: https://help.github.com/articles/creating-releases/
You just create the release, github adds the .zip, .tar.gz for you :-).
If it just takes a few days, we can of course do that after #44 is solved. I'll just wait a little bit more to create the Debian package.

**Comment by victorwestmann** [comment]
It would be simply amazing if this could ship with the final installer/package. It should be enabled when the user selects (at least in Windows) custom or full installation. +1 for this! _o/

**Comment by legrostdg** [comment]
@Xaviju, now that #44 is fixed, is there still something preventing a release of inkscape-open-symbols?

**Comment by Xaviju** [comment]
Everything seems fine now. Should we create the 1.0.0 release?

**Comment by legrostdg** [comment]
sure!

**Comment by legrostdg** [comment]
(or whatever numbering you prefer) 1.0 may be OK, too.

**Comment by Xaviju** [comment]
https://github.com/Xaviju/inkscape-open-symbols/releases/tag/v1.0

**Comment by Moini** [comment]
Congrats :)

(Nitpicking follows: for a release, does it make sense to include all those files? I'd only have put the README, LICENSE and the svgs into it, to make it easy for packagers. Neither gitignore, the gulpfile, the template or the subfolder ordering is relevant for a .deb package, I think.)

**Comment by Xaviju** [comment]
@Moini no, it doesn't. Only SVG files, readme and license seems perfectly enough. If you create the deb package, please add it to the readme and in the #57 issue to add it to the website.

**Comment by legrostdg** [comment]
It doesn't matter too much to have everything in the archive. It's easy to select only */*.svg. My debian package is almost ready :)

**Comment by Xaviju** [comment]
He is added to the issue recently closed. Thanks @PanderMusubi

**Comment by PanderMusubi** [comment]
Would it be possible to get a new release and updated package? We are already two years down the road.
