### ISSUE TITLE
Add isotype

### ISSUE THREAD

**Issue by PanderMusubi** [Xaviju/inkscape-open-symbols#50]
If legally allowed and vectorised version can be found, please add support for isotype, see also http://www.gerdarntz.org/isotype

**Comment by Moini** [comment]
See http://www.gerdarntz.org/content/copyright

Quote:
"The Gerd Arntz web archive is intended for educational and informative purposes only. Any use of any of the images from the website without permission by Pictoright/Gerd Arntz Estate is prohibited."

So no, this doesn't appear to be possible. Of course, you can try to contact the copyright holders, and ask for permission, if you like.

**Comment by Xaviju** [comment]
We cannot share if it has copyright, but its a very interesting set. I'd love to use some of those isotypes.
