### ISSUE TITLE
Python Uniconverter errors/crash

### ISSUE THREAD

**Issue by metanerd** [Xaviju/inkscape-open-symbols#53]
So I copied the *.svg into home/user/.config/inkscape/symbol. 
I open inkscape, open the symbols(shift+control+y) , I select a symbol and drag and drop it onto the inkscape canvas. Several python uniconverter warnings pop up
![uniconverterbug](https://cloud.githubusercontent.com/assets/9913860/21645137/250c4402-d291-11e6-8bba-36df9f43e24a.png)

I don't advise to do this several times. Even xserver crashed for me. I am on linux mint cinnamon. 4.6.0-040600-generic 
I also added latest ppa for inkscape and retried. Same result.

**Comment by metanerd** [comment]
Sorry, it is a package or inkscape bug. just copied a text and it gave me the same result. 
happy new year!

**Comment by Moini** [comment]
It's most probably a problem with your clipboard manager in combination with Inkscape. See also:
https://bugs.launchpad.net/inkscape/+bug/418242

(disable to make it work)

**Comment by metanerd** [comment]
Wow, thank you! Probably would have looked forever. Mh that is annoying.

**Comment by Moini** [comment]
Yes, I know. I've once given a workshop, and one of the participants suffered from this issue. Unfortunately, by then I didn't know how to fix it yet, and it was really annoying... They took it lightly, though, fortunately, and still enjoyed the things that worked :)
