### ISSUE TITLE
Where is symbols folder in Inkscape 0.92? (Mac OSX)

### ISSUE THREAD

**Issue by victorwestmann** [Xaviju/inkscape-open-symbols#56]
Hi Guys. Happy new year!

I'm following instructions of this project to install new symbols in my brand new Inkscape 0.92 on a Mac. However this folder does not seem to exist. (~/.config/inkscape/symbols)

Any advices? Thanks in advance.

**Comment by Moini** [comment]
Create it :)

**Comment by victorwestmann** [comment]
It seems I found it.
Looks like now it is in the following path:

~/inkscape/share/symbols

I'm going to test this first. If it works I will close this. Thanks!

**Comment by victorwestmann** [comment]
You were right @Moini I needed to create the folder: (~/.config/inkscape/symbols)

Now it works. Closing. Thanks for your help!

**Comment by Xaviju** [comment]
Great! :tada:
