### ISSUE TITLE
Invalid svg code in symbol sets

### ISSUE THREAD

**Issue by Moini** [Xaviju/inkscape-open-symbols#58]
su_v, over at launchpad, found a couple of svg code validity errors while triaging the list ordering bug. I'm attaching her cleaned error console output.

[1654902-inkscape-open-symbols-warnings-092x.txt](https://github.com/Xaviju/inkscape-open-symbols/files/692637/1654902-inkscape-open-symbols-warnings-092x.txt)

**Comment by Moini** [comment]
(the pr doesn't fix the warnings unrelated to sjjb, but this was a quick fix right now)

**Comment by su-v** [comment]
Minimal diff to fix remaining warnings: [gist](https://gist.github.com/su-v/d3c37992e4b33a45a9183bce78a666b6)

**Comment by Xaviju** [comment]
@Moini @su-v Wow, that's awesome, thanks for testing it and for the gist! 
I'll fix it ASAP.

**Comment by Xaviju** [comment]
I launched inkscape from terminal with all symbol sets installed and received no errors.

**Comment by Moini** [comment]
(It's not the launch of Inkscape that triggered the errors, it's opening the symbols dialog for the first time, because that is when the symbol sets are read. That said, I only get those SPIStyle warnings now. Not sure what they mean, though.)

Anyway, thank you, @su-v and @Xaviju :)
