### ISSUE TITLE
Rename, improve and extend GNOME Icon Theme Symbolic / GNOME Symbolic Icons

### ISSUE THREAD

**Issue by PanderMusubi** [Xaviju/inkscape-open-symbols#63]
The GNOME icons currently included are from the `GNOME Icon Theme Symbolic` see https://git.gnome.org/browse/gnome-icon-theme-symbolic Please use `symbols` in the name in this project in the filenames and the name of the symbol sets in Inkscape. Now the sets are called `GNOME Icons Theme` and will be confusing with future additional icon themes from GNOME. Please, use `GNOME Symbolic Icons`. I think this is short, accurate and inline with the other names used in this project. The word theme is not needed here.

Please, also extend the currently supported sets `app` and `actions` to all sets, see https://git.gnome.org/browse/gnome-icon-theme-symbolic/tree/gnome/scalable

Note that `app` needs to get renamed to `apps` in some places in this project.

All SVG data van be extracted from the latest official release at https://launchpad.net/gnome-icon-theme-symbolic

(As reference only, the development files are at https://git.gnome.org/browse/gnome-icon-theme-symbolic/tree/src )

**Comment by Xaviju** [comment]
Updated gnome icons with gnome symbolic here https://github.com/Xaviju/inkscape-open-symbols/commit/2173ea24dca2afbfb97ba9fa7bd54143901bded4

Please test before closing the issue
