### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by victorwestmann** [Xaviju/inkscape-open-symbols#69]
Hi there, wouldn't it be amazing if we could put the instructions on how to CREATE the Inkscape open symbols icon sets in the Wiki of this project? Alongside video instructions as well. We need to open the doors for volunteers. What do you guys think?

**Comment by Xaviju** [comment]
I'd love it. 
- I created a blog post on how to create the symbols set manually (hard work) for those who does not have a development knowledge https://medium.com/@xaviju/creating-your-own-symbol-library-in-inkscape-0-91-and-make-your-front-end-developer-you-338588137aaf
- I've created some automated tasks here to do most of the ugly work: https://github.com/Xaviju/inkscape-open-symbols/blob/master/gulpfile.js
If this could be compiled into some sort of step to step guide would be so useful.

A video would be just amazing, but English is not my mother tongue so probably sounds funny.

**Comment by victorwestmann** [comment]
I agree with you that a video would be amazing. It would give us minimal
work to do and would speed up things for newcomers.

My current machine, however, has a lot of problems and cannot use a
dedicated graphics card driver. Would you mind if I documented this in
images and numbered instructions for now?



--Victor Westmann

2017-04-13 12:34 GMT-07:00 Xaviju <notifications@github.com>:

**Comment by Xaviju** [comment]
@victorwestmann A storyboard would be very helpful :) 

If anyone is interested in helping out with the text instructions they could also document the many different ways for creating a symbol set.

**Comment by PanderMusubi** [comment]
I would like to help. Also on creating some screencasts.

**Comment by Xaviju** [comment]
I am really busy this month and I cannot take the initiative at this moment so thanks @PanderMusubi and @victorwestmann, please let me know if do you need anything to start with this from me.  I will gladly help you as soon as possible.
I volunteer to write the steps using automation tools as gulp, but we could start simply by creating instructions on how to create symbol sets:
- [Using the Inkscape Interface](https://www.youtube.com/watch?v=jdaGB0zCdHw) (Note: It has its downsides, like icons not being editable)
- [Handmade process](https://medium.com/@xaviju/creating-your-own-symbol-library-in-inkscape-0-91-and-make-your-front-end-developer-you-338588137aaf)
- [Later] Using automation task tools such as Gulp

About the video, I'd rather focus on the Handmade process since is the most useful for designers, developers and all kind of users. 
Let me know what you think.

**Comment by victorwestmann** [comment]
Hi @Xaviju. Not a problem. At all. It's a pleasure to help and contribute with this project. I strongly believe this is very useful for the Inkscape project and that it can convert a lot of new users to the app.

The only thing I would change is to get images of all the steps, and number all the steps. I would give an example with only one symbol though.

The initial instructions I made, all extracted from one of your videos, are here (see below).

HOW TO USE SYMBOLS

1. Open Inkscape.
2. Go to "Object" > "Symbol..." (Shift + Ctrl + Y) to open the Symbols dialog panel.
3. Drag objects from the Symbol panel to the Inkscape canvas. 
4. Voilá!

HOW TO CREATE SYMBOLS

1. Make sure your SVG object is ready in your canvas.
2. Right click in your SVG pbject and go to > "Object Properties...".
3. Change the "ID" field of your SVG object.
4. Click on "Set" to apply the new name to your future Symbol.
5. Now with the object(s) ready on the canvas and with the desired name applied you should only left click the object and to to the left arrow in the bottom left of the Symbols panel.
As soon as you click the left arrow the object will be added to your new collection of Symbols

HOW TO SETUP A LICENSE FOR YOUR SYMBOLS

1. Open Inkscape
2. Go to "File" > "Document Properties..." > Click on the "Metadata" tab.
3. Fill in the "Title", "Date", "Creator" and all the relevant fields
4. Next go to the "License" tab and choose your desired license.

SAVING YOUR NEW SYMBOL SET

If you are on Linux environment do the following
1. Go to "File" > "Save" > Press Ctrl + H on the keyboard
2. ~/.config/inkscape/symbols
3. choose the desired name of your SVG file and save it as an "Inkscape SVG (*.svg)" file.

HOW TO USE YOUR NEWLY CREATED SYMBOL SET?
1. Close Inkscape
2. Reopen Ikscape
3. GO to the Symbols dialog panel (Shift + Ctrl + Y) or go to "Object" > "Symbols" and search for the name of your file on the dropdown menu of Symbol Sets.
4. Voilá!

**Comment by Xaviju** [comment]
@victorwestmann nice.
This is the perfect explanation on how to create a symbol library from the Inkscape UI. It solves the first option, and probably one of the most common user flow for designers. 
In my opinion you probably don't need to use images for every step, but a representative one of the _HOW TO..._ section in most of the cases. Its quite self-explanatory.

Do you have acces to the wiki? Should I give you any permissions to edit? Let me know how to help.

For web developers + designers I could try to create the more detailed version with minimized, editable SVG files. But for the moment, this is quite useful.

**Comment by victorwestmann** [comment]
Hi @Xaviju thank you for this. I created the first draft of the instructions on the Wiki of this project. Let me know if you want anything changed/different. It's a true pleasure to be able to collaborate to this project! <3

**Comment by victorwestmann** [comment]
Hi @Xaviju and @PanderMusubi is there anything else you guys want me to do on this particular issue? Can I close this request?
