### ISSUE TITLE
Upgrade octicons

### ISSUE THREAD

**Issue by PanderMusubi** [Xaviju/inkscape-open-symbols#70]
Please upgrade octicons to latest version from https://github.com/primer/octicons/releases/

**Comment by Xaviju** [comment]
Great! Thanks for the heads up!

**Comment by Xaviju** [comment]
Working on this!

**Comment by Xaviju** [comment]
Closed here https://github.com/Xaviju/inkscape-open-symbols/commit/66e3eb4f60c7e93ce25c7ae9363dc39a621987ef
