### ISSUE TITLE
Can't open Font-Awesome

### ISSUE THREAD

**Issue by romu70** [Xaviju/inkscape-open-symbols#71]
Hello,
I'm trying to open the font-awesome.svg from my mac, here are the results of my tries:

- Sketch -> Crash
- Gravit Designer -> "Can't open the file"
- Firefox -> 

```
XML Parsing Error: not well-formed
Location: file:///Users/romuald/Downloads/font-awesome.svg
Line Number 35, Column 91:  <meta name="request-id" content="CD69:05A2:6034A2C:8EA8D5F:592FE944" data-pjax-transient>
------------------------------------------------------------------------------------------^
```

I'll try with Inkscape as soon as I've access ot my Fedora station.

**Comment by Xaviju** [comment]
Sorry @romu70 I have no idea how Sketch or Gravit handle SVG sprites. 
Opening an SVG sprite in Firefox should not display anything but a blank page. Anyway, I'm not getting any errors, is it happening with other symbols as well?

Let me know if it works in Inkscape following the instructions in the README

**Comment by romu70** [comment]
My bad, I downloaded the html and not the SVG directly.

I re-tried with the correct SVG, and none of those 3 software handle the file correcly. Sketch and Firefox -> blank page, and Gravit refuses to open it.

**Comment by Xaviju** [comment]
Not displaying anything (or blank) does not mean that they don't handle it correctly.
This is the SVG sprite, so it should not display anything. Would be interesting to know if Gravit or Sketch support standard SVG sprites for symbols and how.

**Comment by romu70** [comment]
We can ask them.
