### ISSUE TITLE
Namespace prefix problems

### ISSUE THREAD

**Issue by danmaz74** [Xaviju/inkscape-open-symbols#73]
I installed the symbols; most of them work and are great, but for font awesome and many suru icons I get:

`/home/daniele/.config/inkscape/symbols/font-awesome.svg:6: namespace error : Namespace prefix cc on Work is not defined
            <cc:Work rdf:about="">
                                 ^
/home/daniele/.config/inkscape/symbols/font-awesome.svg:12: namespace error : Namespace prefix cc on Agent is not defined
                    <cc:Agent>
                             ^
/home/daniele/.config/inkscape/symbols/font-awesome.svg:17: namespace error : Namespace prefix cc on Agent is not defined
                    <cc:Agent>
                             ^
/home/daniele/.config/inkscape/symbols/suru-icons-status.svg:4024: namespace error : Namespace prefix xlink for href on use is not defined
orm="translate(-283.57143,-1916.4285)" id="use13962" xlink:href="#airplane-mode"
                                                                               ^
/home/daniele/.config/inkscape/symbols/suru-icons-status.svg:4025: namespace error : Namespace prefix xlink for href on use is not defined
form="translate(-156.43675,-914.41069)" id="use13982" xlink:href="#alarm-missed"
                                                                               ^
/home/daniele/.config/inkscape/symbols/suru-icons-status.svg:4026: namespace error : Namespace prefix xlink for href on use is not defined
"translate(-103.57144,-1916.4285)" id="use14010" xlink:href="#audio-output-none"
`

Version: Inkscape 0.91 r13725
OS: Ubuntu 16

**Comment by Xaviju** [comment]
Thanks for reporting.

**Comment by Xaviju** [comment]
I think this PR https://github.com/Xaviju/inkscape-open-symbols/pull/77 fixes it. Please test it.
Thanks!
