### ISSUE TITLE
Add Iron Icons

### ISSUE THREAD

**Issue by mairin** [Xaviju/inkscape-open-symbols#75]
https://github.com/PolymerElements/iron-iconset-svg
They are BSD-licensed.

**Comment by Xaviju** [comment]
@mairin I don't know Polymer very well but seems that this is a component for creating SVG sprites. Does not seem to include any SVG icons by itself. 
Polymer, and other google products promote the material design icons that are already available here (a bit outdated, sorry).
Please, let me know what I am missing. Thanks!

**Comment by PanderMusubi** [comment]
Perhaps politely notify them their build is failing. Better to use a successful build as a starting point for here.

**Comment by mairin** [comment]
@Xaviju ah my apologies! I don't actually work with the material icon set a lot so i didn't realize it was the same. You can disregard this, I'll close it :)

**Comment by Xaviju** [comment]
@mairin No problem! thanks for contributing :)
