### ISSUE TITLE
CircuiTikz symbols scrambled

### ISSUE THREAD

**Issue by bahram-houchmandzadeh** [Xaviju/inkscape-open-symbols#78]
Installed electronic symbols (CircuiTikz) appear completely scrambled and useless (see screenshot attached). All other symbols tested appear fine. 
System : Ubuntu 17.04
Inkscape : 0.92.1

![circuitikz](https://user-images.githubusercontent.com/18464285/32884151-afd262f8-cab9-11e7-9de2-92b15f3eaa61.png)

**Comment by Xaviju** [comment]
Sorry, I have no knowledge of electrical symbols. It actually looks like is broken or bad-formed. It was created at #68 by @joel-jose 
I'll review the code but I'll need help to find out what each symbol means and how should it look.

**Comment by joel-jose** [comment]
I'll take a look at them asap.

**Comment by joel-jose** [comment]
This is caused by #77. Line 12 of the SVG file `style="fill:none;stroke:black; stroke-width:3px;"` was overwritten to `style="fill:black;stroke:none"`which broke the symbols. I'll create a pull request with the fixed symbols.

**Comment by Xaviju** [comment]
That was fast! Thanks @joel-jose

**Comment by bahram-houchmandzadeh** [comment]
Thank you a lot. The problem is indeed solved.
