### ISSUE TITLE
CircuiTikz is not public domain

### ISSUE THREAD

**Issue by legrostdg** [Xaviju/inkscape-open-symbols#85]
I'm preparing the update to 1.2 of the Debian package. According to https://github.com/circuitikz/circuitikz, the copyright is:

    Copyright 2007-16 by Massimo Redaelli
    
    This file may be distributed and/or modified
    
        under the LaTeX Project Public License and/or
        under the GNU Public License.

So, definitely not public domain. Could you update the info on the README?

**Comment by Xaviju** [comment]
According to the creator of the symbol package, it comes from this Public Domain file https://commons.wikimedia.org/wiki/File:Electrical_symbols_library.svg

Might be PD the SVG file but not the TeX/LaTeX package? 🤔

**Comment by legrostdg** [comment]
Is this svg file really CircuiTikz? It is not mentioned anywhere on the page.

**Comment by joel-jose** [comment]
Hi,
The SVG contains symbols both from the wiki page and CircuiTikZ. I had contacted Massimo regarding this, he had replied saying the package is now maintained by Lindner and Erhardt Stefan. They haven't replied to my query regarding the use of individual symbols. The license refers to the LaTeX package.

**Comment by legrostdg** [comment]
I'm sure public domain + gpl/latex does not equal to public domain...

**Comment by Xaviju** [comment]
Ok, so I was wrong, sorry for the misunderstanding. 
Please correct me if I am wrong but if the CircuiTikZ is GPL3 and the other symbols are public Domain this symbol set can be redistributed as a derivated work from CircuiTikZ with a GPL3 license.
I can fix that in the readme and in the file if you agree.

**Comment by Xaviju** [comment]
Recently spoke with a person with vast knowledge about licenses and his recommendation is to convert all the CircuiTikZ icon set to GPL3 license as I thought.
I'll do it as soon as possible and release a new version.

**Comment by Xaviju** [comment]
Fixed and released!

**Comment by legrostdg** [comment]
I'm not sure about the licensing... Could you update the README with the valid CircuitTikz license? Who is the copyright holder of the icon set in inkscape-open-symbols? Did he agreed to change the license or did you just change it yourself?

**Comment by legrostdg** [comment]
OK, you used the license from  https://github.com/circuitikz/circuitikz

**Comment by Xaviju** [comment]
Yes @legrostdg sorry if I did not updated the README. I'll do it asap.
Since some of the icons are public domain and some of them are from circuitikz (GPLv3) I've used the circuitikz license.
