### ISSUE TITLE
Update emojione to version 4.0

### ISSUE THREAD

**Issue by PanderMusubi** [Xaviju/inkscape-open-symbols#97]
Please, update emojione to version 4.0

**Comment by Xaviju** [comment]
Trying to download the version 4 SVG files but I was not able to do it: https://www.emojione.com/download
Is it still open source?

**Comment by meetdilip** [comment]
It is not. They only give PNG these days. That too personal use / generate no revenue.

**Comment by Xaviju** [comment]
Ok. Closing this issue.
Thanks!
